// frontend/src/components/brochure/Brochure.tsx
import React from "react";
// import "./WhyChooseUs.css";


function Brochure() {
  return (
    <section className="why-choose-us py-5 text-center justify-content-center">
      <div className="container-3 mt--70 mb--30">
        <div className="row">
            <div className="col-lg-12 justify-content-center">
                <div className="title-area-left text-center pl--0">
                    <h2 className="title-center">Click on the Download Button to Download MRS product Brochure</h2>
                    <a className="btn m-2 btn-primary btn-lg p-3"><i className="fas fa-download"></i> Download Brochure</a>
                </div>
            </div>

        </div>
       
      </div>
    </section>
  );
}

export default Brochure;

// src/components/common/Brochure.vue
<template>
    <section class="py-16 bg-white">
            <div class="container mx-auto px-4 text-center">
                <h2 class="text-2xl font-bold mb-2">Click on the Download Button to Download MRS product Brochure</h2>
                <RouterLink to="/about"
                    class="inline-flex items-center gap-2 bg-primary text-white mt-12 px-5 py-2 rounded hover:bg-gray-100 transition">
                    <font-awesome-icon icon="download" />
                    <span>Download Brochure</span>

                </RouterLink>
            </div>
        </section>
</template>
